"""
Energy mix optimization using Pyomo.

Solves a unit commitment / economic dispatch problem: given a portfolio of
generators (coal, gas, wind, solar, etc.) and an hourly demand curve, find
the cheapest generation schedule that meets demand in every period while
respecting each unit's capacity limits and, optionally, a system-wide
CO2 emission cap.

Input schema
------------
{
  "generators": [
    {
      "id":             string   -- unique identifier
      "pmin":           float    -- minimum output when on (MW)
      "pmax":           float    -- maximum output when on (MW)
      "variable_cost":  float    -- fuel cost ($/MWh)
      "fixed_cost":     float    -- no-load cost when online ($/h)
      "emission_rate":  float    -- CO2 intensity (tonne/MWh); 0 for renewables
      "renewable":      bool     -- if true, unit is always-on (no binary)
    },
    ...
  ],
  "demand":          [float, ...]  -- demand for each time period (MW)
  "emission_limit":  float | null  -- optional system CO2 cap (tonnes, total)
}

Output schema
-------------
{
  "schedule": [
    {
      "generator_id": string,
      "time_period":  int,
      "power_mw":     float,
      "status":       "on" | "off"
    }, ...
  ],
  "summary": {
    "total_cost_usd":       float,
    "total_emissions_t":    float,
    "periods":              int,
    "generators":           int
  }
}
"""

import hashlib
import sys
import time

import nextmv
from nextmv import Asset, Manifest, Visual, VisualSchema
import pyomo.environ as pyo

# Map solver names to their time-limit option keys.
SUPPORTED_PROVIDERS = {
    "cbc": "sec",
    "glpk": "tmlim",
    "highs": "time_limit",
    "scip": "limits/time",
}

STATUS = {
    pyo.TerminationCondition.feasible: "suboptimal",
    pyo.TerminationCondition.infeasible: "infeasible",
    pyo.TerminationCondition.optimal: "optimal",
    pyo.TerminationCondition.unbounded: "unbounded",
}

manifest = Manifest.from_yaml(".")
options = manifest.extract_options()


def main() -> None:
    """Entry point for the program."""

    input = nextmv.load(options=options)

    generators = input.data.get("generators", [])
    demand = input.data.get("demand", [])

    nextmv.log("Solving energy dispatch problem:")
    nextmv.log(f"  - generators : {len(generators)}")
    nextmv.log(f"  - time periods: {len(demand)}")
    nextmv.log(f"  - emission cap: {input.data.get('emission_limit', 'none')}")
    nextmv.log(f"  - emission multiplier: {options.emission_multiplier}")

    model = EnergyDispatchModel()
    output = model.solve(input)
    nextmv.write(output)


class EnergyDispatchModel(nextmv.Model):
    def solve(self, input: nextmv.Input) -> nextmv.Output:
        """Build and solve the unit-commitment model, return a Nextmv Output."""

        start_time = time.time()

        provider = input.options.provider
        if provider not in SUPPORTED_PROVIDERS:
            raise ValueError(
                f"Unsupported provider: {provider}. "
                f"Supported: {', '.join(SUPPORTED_PROVIDERS)}"
            )

        generators = input.data["generators"]
        demand = input.data["demand"]
        raw_limit = input.data.get("emission_limit", None)
        multiplier = input.options.emission_multiplier
        if multiplier is None:
            multiplier = 1.0
        if raw_limit is None or multiplier < 0:
            emission_limit = None
        else:
            emission_limit = raw_limit * multiplier

        gen_ids = [g["id"] for g in generators]
        gen_map = {g["id"]: g for g in generators}
        periods = list(range(len(demand)))

        # Partition generators: renewables are always available (no on/off);
        # thermal units get a binary commitment variable.
        renewable_ids = [g["id"] for g in generators if g.get("renewable", False)]
        thermal_ids = [g["id"] for g in generators if not g.get("renewable", False)]

        # ------------------------------------------------------------------ #
        # Build Pyomo model                                                    #
        # ------------------------------------------------------------------ #
        m = pyo.ConcreteModel(name="EnergyDispatch")

        # Sets
        m.G = pyo.Set(initialize=gen_ids)
        m.T = pyo.Set(initialize=periods)

        # Decision variables
        # power[g, t] — MW generated by unit g in period t
        m.power = pyo.Var(m.G, m.T, domain=pyo.NonNegativeReals)

        # on[g, t] — binary commitment for thermal units
        if thermal_ids:
            m.on = pyo.Var(thermal_ids, m.T, domain=pyo.Binary)

        # ------------------------------------------------------------------ #
        # Objective: minimise total cost                                       #
        # ------------------------------------------------------------------ #
        def total_cost(m):
            cost = 0.0
            for g in gen_ids:
                vc = gen_map[g]["variable_cost"]
                fc = gen_map[g].get("fixed_cost", 0.0)
                for t in periods:
                    cost += vc * m.power[g, t]
                    if g in thermal_ids:
                        cost += fc * m.on[g, t]
            return cost

        m.objective = pyo.Objective(rule=total_cost, sense=pyo.minimize)

        # ------------------------------------------------------------------ #
        # Constraints                                                          #
        # ------------------------------------------------------------------ #

        # 1. Demand balance: total generation must meet demand each period.
        def demand_balance(m, t):
            return sum(m.power[g, t] for g in gen_ids) == demand[t]

        m.demand_balance = pyo.Constraint(m.T, rule=demand_balance)

        # 2. Thermal capacity: output is between pmin and pmax when on.
        def thermal_min(m, g, t):
            return m.power[g, t] >= gen_map[g]["pmin"] * m.on[g, t]

        def thermal_max(m, g, t):
            return m.power[g, t] <= gen_map[g]["pmax"] * m.on[g, t]

        if thermal_ids:
            m.thermal_min = pyo.Constraint(thermal_ids, m.T, rule=thermal_min)
            m.thermal_max = pyo.Constraint(thermal_ids, m.T, rule=thermal_max)

        # 3. Renewable capacity: output bounded by pmax (no binary).
        def renewable_max(m, g, t):
            return m.power[g, t] <= gen_map[g]["pmax"]

        if renewable_ids:
            m.renewable_max = pyo.Constraint(renewable_ids, m.T, rule=renewable_max)

        # 4. Optional CO2 emission cap.
        if emission_limit is not None:
            def emission_cap(m):
                return (
                    sum(
                        gen_map[g].get("emission_rate", 0.0) * m.power[g, t]
                        for g in gen_ids
                        for t in periods
                    )
                    <= emission_limit
                )

            m.emission_cap = pyo.Constraint(rule=emission_cap)

        # ------------------------------------------------------------------ #
        # Solve                                                                #
        # ------------------------------------------------------------------ #
        solver = pyo.SolverFactory(provider)
        solver.options[SUPPORTED_PROVIDERS[provider]] = input.options.duration
        results = solver.solve(m, tee=sys.stderr)

        # ------------------------------------------------------------------ #
        # Extract solution                                                     #
        # ------------------------------------------------------------------ #
        obj_value = pyo.value(m.objective, exception=False)
        total_emissions = 0.0
        schedule = []

        if obj_value is not None:
            for g in gen_ids:
                er = gen_map[g].get("emission_rate", 0.0)
                for t in periods:
                    pwr = pyo.value(m.power[g, t], exception=False) or 0.0
                    if g in thermal_ids:
                        status = "on" if (pyo.value(m.on[g, t], exception=False) or 0) > 0.5 else "off"
                    else:
                        status = "on" if pwr > 0 else "off"
                    total_emissions += er * pwr
                    schedule.append(
                        {
                            "generator_id": g,
                            "time_period": t,
                            "power_mw": round(pwr, 4),
                            "status": status,
                        }
                    )

        tc = results.solver.termination_condition
        try:
            solver_time = float(results.solver.time)
        except Exception:
            try:
                solver_time = float(results.solver.wallclock_time)
            except Exception:
                solver_time = None

        metrics = {
            "run_duration": time.time() - start_time,
            "duration": solver_time,
            "value": obj_value,
            "status": STATUS.get(tc, "unknown"),
            "variables": m.nvariables(),
            "constraints": m.nconstraints(),
            "total_cost_usd": round(obj_value, 2) if obj_value is not None else None,
            "total_emissions_t": round(total_emissions, 2),
            "periods": len(periods),
            "generators": len(gen_ids),
        }
        assets = [build_generation_chart(schedule, gen_ids, periods, demand)]

        return nextmv.Output(
            options=options,
            solution={"schedule": schedule},
            metrics=metrics,
            assets=assets,
        )


_GENERATOR_COLORS = [
    "rgba(59,130,246,0.8)",   # blue
    "rgba(234,88,12,0.8)",    # orange
    "rgba(22,163,74,0.8)",    # green
    "rgba(168,85,247,0.8)",   # purple
    "rgba(234,179,8,0.8)",    # yellow
    "rgba(239,68,68,0.8)",    # red
    "rgba(20,184,166,0.8)",   # teal
    "rgba(249,115,22,0.8)",   # amber
]


def build_generation_chart(
    schedule: list[dict],
    gen_ids: list[str],
    periods: list[int],
    demand: list[float],
) -> Asset:
    """Build a Chart.js stacked bar chart showing MW output per generator per hour."""

    # Index power by (generator_id, time_period) for fast lookup.
    power_index: dict[tuple[str, int], float] = {}
    for entry in schedule:
        power_index[(entry["generator_id"], entry["time_period"])] = entry["power_mw"]

    labels = [f"Hour {t}" for t in periods]

    datasets = []
    for gid in gen_ids:
        idx = int(hashlib.md5(gid.encode()).hexdigest(), 16) % len(_GENERATOR_COLORS)
        color = _GENERATOR_COLORS[idx]
        datasets.append(
            {
                "label": gid,
                "data": [power_index.get((gid, t), 0.0) for t in periods],
                "backgroundColor": color,
                "borderColor": color.replace("0.8", "1"),
                "borderWidth": 1,
            }
        )

    # Add demand as a line overlay.
    datasets.append(
        {
            "type": "line",
            "label": "Demand",
            "data": list(demand),
            "borderColor": "rgba(0,0,0,0.85)",
            "backgroundColor": "rgba(0,0,0,0)",
            "borderWidth": 2,
            "pointRadius": 2,
            "order": 0,
        }
    )

    chart_data = {
        "type": "bar",
        "data": {"labels": labels, "datasets": datasets},
        "options": {
            "responsive": True,
            "plugins": {
                "title": {
                    "display": True,
                    "text": "Generation Schedule by Source",
                },
                "legend": {"position": "bottom"},
            },
            "scales": {
                "x": {"stacked": True, "title": {"display": True, "text": "Hour"}},
                "y": {
                    "stacked": True,
                    "title": {"display": True, "text": "Power (MW)"},
                    "beginAtZero": True,
                },
            },
        },
    }

    return Asset(
        name="generation_schedule_chart",
        description="Stacked bar chart of MW output per generator per hour, with demand overlay",
        content=chart_data,
        visual=Visual(
            visual_schema=VisualSchema.CHARTJS,
            label="Generation Schedule",
        ),
    )


if __name__ == "__main__":
    main()
