# This manifest holds the information the app needs to run on the Nextmv Cloud.
type: python
runtime: ghcr.io/nextmv-io/runtime/python:3.11
python:
  # All listed packages will get bundled with the app.
  pip-requirements: requirements.txt

# List all files/directories that should be included in the app. Globbing
# (e.g.: configs/*.json) is supported.
files:
  - main.py
  - visuals.py
  - uc.mod
  - ampl_license_uuid.txt

configuration:
  content:
    format: "multi-file"
    multi-file:
      input:
        path: "."
      output:
        statistics: "statistics.json"
        assets: "assets.json"
        solutions: "."
  options:
    items:
      - name: solver
        option_type: string
        default: "highs"
        additional_attributes:
          values:
            - gurobi
            - highs
        ui:
          control_type: select
      - name: solver_options
        option_type: string
        default: "outlev=1 timelim=30 threads=16"
        ui:
          control_type: input
      - name: demand_multiplier
        option_type: float
        default: 1.0
        ui:
          control_type: slider
        additional_attributes:
          min: 0.75
          max: 1.70
          step: 0.01
